<footer class="clearfix">
    <section class="aside">
        <img id="LogoWeb" src="/images/LogoWeb.png"/>
    </section>

    <aside id="privacy" class="div">
        <p>Alessandro Brancaleoni
        <br/>
        Handball Shop - <a style="color: #35333f;" href="https://www.unife.it/ing/lm.infoauto/ing-sw-ii">Ingegneria del Software Avanzata</a> - 2022
        <br/>
        Handball Shop - <a style="color: #35333f;" href="https://www.unife.it/ing/lm.infoauto/Tecnologie-basi-dati">Tecnologie per le Basi di Dati</a> - 2022
        <br/>
        <a style="color: #35333f;" href="http://www.unife.it/">Universit&agrave; degli Studi di Ferrara</a><br/></p>
    </aside>
</footer>